// react/react-other/src/App.js
import React from 'react';
import HookDemo from './components/HookDemo/HookDemo';
// import Header from './components/LoginDemo/Header';
// import ContextDemo from './components/ContextDemo/ContextDemo';

function App () {
  return (
    <div className="App">
      {/* <ContextDemo /> */}
      {/* <Header /> */}
      <HookDemo />
    </div>
  );
}

export default App;

// vue/vue-ts-shequ/src/App.vue
<template>
  <div id="app">
    <Header />
    <router-view></router-view>
  </div>
</template>
<script lang='ts'>
import { Component, Vue } from 'vue-property-decorator'
import Header from './components/Header.vue'
@Component({
  components: {
    Header
  }
})
export default class App extends Vue { }
</script>
<style lang="scss" scoped>
</style>
