// react/react-todo/src/components/TodoFooter.js
import React from 'react'
const TodoFooter = ({ showType, changeType, activeTodoNum, clearCompleted }) => <div>
  <span>{activeTodoNum} {activeTodoNum === 1 ? 'item' : 'items'} left</span>
  <button onClick={() => changeType('all')} style={{ color: showType === 'all' ? 'red' : 'black' }}>All</button>
  <button onClick={() => changeType('active')} style={{ color: showType === 'active' ? 'red' : 'black' }}>Active</button>
  <button onClick={() => changeType('completed')} style={{ color: showType === 'completed' ? 'red' : 'black' }}>Completed</button>
  <button onClick={clearCompleted}>Clear Completed</button>
</div>
export default TodoFooter

// vue/vue-todo/src/components/TodoFooter.vue
<template>
  <div class="todo-footer">
    <span>
      {{ activeTodosNum }} item{{ activeTodosNum === 1 ? "" : "s" }} left
    </span>
    <div>
      <button
        @click="$emit('changeType', 'all')"
        :class="{ active: showType === 'all' }"
      >
        all
      </button>
      <button
        @click="$emit('changeType', 'active')"
        :class="{ active: showType === 'active' }"
      >
        active
      </button>
      <button
        @click="$emit('changeType', 'completed')"
        :class="{ active: showType === 'completed' }"
      >
        completed
      </button>
    </div>
    <button @click="$emit('clearCompleted')">clear completed</button>
  </div>
</template>

<script>
export default {
  name: 'TodoFooter',
  props: ['activeTodosNum', 'showType']
}
</script>

<style scoped>
.todo-footer {
  display: flex;
  justify-content: space-between;
  padding: 10px;
}
.active {
  color: red;
}
</style>
