// vue/vuex-todo/src/App.vue
<template>
  <div id="app">
    <h2>hello vuex todo</h2>
    <TodoForm />
    <TodoList />
  </div>
</template>

<script>

import TodoForm from './components/TodoForm'
import TodoList from './components/TodoList'
export default {
  name: 'App',
  components: {
    TodoForm,
    TodoList
  },
}
</script>

<style>
</style>

// react/react-state/src/App.js
import React from 'react';
import Count from './components/Count'
import Box from './components/Box/Box'
import Drawer from './components/Drawer'
function App () {
  return (
    <div className="App">
      <h1>hello</h1>
      <Count />
      <hr />
      <Box />
      <hr />
      <Drawer />
    </div>
  );
}

export default App;
