// vue/vue-todo/src/components/TodoFooter.vue
<template>
  <div class="todo-footer">
    <span>
      {{ activeTodosNum }} item{{ activeTodosNum === 1 ? "" : "s" }} left
    </span>
    <div>
      <button
        @click="$emit('changeType', 'all')"
        :class="{ active: showType === 'all' }"
      >
        all
      </button>
      <button
        @click="$emit('changeType', 'active')"
        :class="{ active: showType === 'active' }"
      >
        active
      </button>
      <button
        @click="$emit('changeType', 'completed')"
        :class="{ active: showType === 'completed' }"
      >
        completed
      </button>
    </div>
    <button @click="$emit('clearCompleted')">clear completed</button>
  </div>
</template>

<script>
export default {
  name: 'TodoFooter',
  props: ['activeTodosNum', 'showType']
}
</script>

<style scoped>
.todo-footer {
  display: flex;
  justify-content: space-between;
  padding: 10px;
}
.active {
  color: red;
}
</style>

// react/react-redux-todo/src/components/TodoFooter.js
import React from 'react'
const TodoFooter = ({ filterType, changeType, activeTodosNum, clearCompleted, completedTodosNum }) => <div><span> {activeTodosNum} item{activeTodosNum === 1 ? '' : 's'} left</span>
  <button onClick={() => changeType('all')} style={{ color: filterType === 'all' ? 'red' : 'black' }}>all</button>
  <button onClick={() => changeType('active')} style={{ color: filterType === 'active' ? 'red' : 'black' }}>active</button>
  <button onClick={() => changeType('completed')} style={{ color: filterType === 'completed' ? 'red' : 'black' }}>completed</button>
  {completedTodosNum ? <button onClick={clearCompleted}>clear completed</button> : ''}
</div>
export default TodoFooter
