// react/react-redux-todo/src/components/TodoList.js
import React from 'react'
import Todo from './Todo'
const TodoList = ({ todos, toggleTodo, delTodo }) => {

  return <div>
    {
      todos.length ? <ul>
        {todos.map(item => <Todo delTodo={delTodo} toggleTodo={toggleTodo} {...item} key={item.id} />)}
      </ul>
        :
        <div>暂无待办事项</div>
    }
  </div>
}
export default TodoList

// vue/vuex-todo/src/components/TodoList.vue
<template>
  <div v-if="todos.length" class="todo-list">
    <Todo v-for="todo in todos" :key="todo.id" :todo="todo" />
  </div>
  <div v-else>暂无待办事项</div>
</template>

<script>
import { mapState } from 'vuex';
import Todo from './Todo'
export default {
  name: 'TodoList',
  components: {
    Todo,
  },
  computed: mapState(['todos']),
}
</script>

<style>
</style>
