// vue/vue-ts-shequ/src/App.vue
<template>
  <div id="app">
    <Header />
    <router-view></router-view>
  </div>
</template>
<script lang='ts'>
import { Component, Vue } from 'vue-property-decorator'
import Header from './components/Header.vue'
@Component({
  components: {
    Header
  }
})
export default class App extends Vue { }
</script>
<style lang="scss" scoped>
</style>

// react/react-router-demo/src/App.js
import React from 'react';
import Header from './components/Header/Header'
import { BrowserRouter as Router } from 'react-router-dom'
import Main from './components/Main/Main';
import 'moment/locale/zh-cn'
import moment from 'moment'
// 全局设置  moment 的语言 设置一次就够了
moment.locale('zh-cn')

function App () {
  return (
    <Router>
      <Header />
      <Main />
    </Router>
  );
}
export default App;
