// vue/vue-ts-shequ/src/App.vue
<template>
  <div id="app">
    <Header />
    <router-view></router-view>
  </div>
</template>
<script lang='ts'>
import { Component, Vue } from 'vue-property-decorator'
import Header from './components/Header.vue'
@Component({
  components: {
    Header
  }
})
export default class App extends Vue { }
</script>
<style lang="scss" scoped>
</style>

// react/react-shequ/src/App.js
import React from 'react';
import Header from './components/Header/Header';
import Main from './components/Main/Main';
import { BrowserRouter as Router } from 'react-router-dom';


function App () {
  return (
    <div className="App">
      <Router>
        <Header />
        <Main />
      </Router>
    </div>
  );
}

export default App;
